const mongoose = require("mongoose");

const orderSchema = new mongoose.Schema({
  customer_id: String,
  store: String,
  order: {
    orderLocation: String,
    uniqueKey: String,
    orderNo: String,
    orderType: String,
    paymentType: String,
    awbNo: String,
    status: String,
    holdStatus: String,
    addressVerified: String,
    paymentVerified: String,
    addressType: String,
    orderDate: String,
    shipbyDate: String,
    orderAmount: String,
    orderCurrency: String,
    conversionRate: String,
    isReplacement: String,
    originalOrderNo: String,
    extCustomerCode: String,
    customerName: String,
    shipAddress1: String,
    shipAddress2: String,
    shipAddress3: String,
    shipAddress4: String,
    shipCity: String,
    shipState: String,
    shipCountry: String,
    shipPinCode: String,
    shipPhone1: String,
    shipPhone2: String,
    shipEmail1: String,
    shipEmail2: String,
    billName: String,
    billAddress1: String,
    billAddress2: String,
    billAddress3: String,
    billAddress4: String,
    billCity: String,
    billState: String,
    landmark: String,
    latitude: String,
    longitude: String,
    url: String,
    billCountry: String,
    billPinCode: String,
    billPhone1: String,
    billPhone2: String,
    billEmail1: String,
    billEmail2: String,
    orderRemarks: String,
    shippingCharges: String,
    otherCharge1: String,
    otherCharge2: String,
    storeCredit: String,
    otherDiscount: String,
    discountCode: String,
    cancelRemark: String,
    isGiftWrap: String,
    giftWrapMsg: String,
    deliverySlot: String,
    udf1: String,
    udf2: String,
    udf3: String,
    udf4: String,
    udf5: String,
    udf6: String,
    udf7: String,
    udf8: String,
    udf9: String,
    udf10: String,
    custTinNo: String,
    pickAfterDate: String,
    giftwrapCharge: String,
    gvAmount: String,
    rewardPointsAmount: Number,
    custType: String,
    isB2B: String,
    reqType: String,
    pickupLocation: String,
    orderProcessing: String,
    userConsent: String,
    items: [
      {
        lineno: String,
        sku: String,
        channelSkuCode: String,
        channelProductId: String,
        orderQty: String,
        cancelledQty: String,
        unitPrice: String,
        bundleSku: String,
        bundlePrice: String,
        bundleQty: String,
        mrp: String,
        discountAmt: String,
        giftVoucherAmt: String,
        shippingCharges: String,
        otherCharge1: String,
        transporter: String,
        storeCredit: String,
        isGiftcard: String,
        vendor: String,
        mode: String,
        taxInclusive: String,
        taxPercentage: String,
        udf1: String,
        udf2: String,
        udf3: String,
        udf4: String,
        udf5: String,
        locationCode: String,
        delFulfillmentMode: String,
        shipmentType: String,
        uom: String,
        discountPercent: String
      }
    ],
    paymentItems: [
      {
        paymentMode: String,
        docNo: String,
        docDate: String,
        docBank: String,
        ifscCode: String,
        docAmt: String,
        amountReceived: String,
        branch: String,
        authCode: String,
        edcNo: String,
        udf1: String,
        udf2: String,
        udf3: String,
        udf4: String,
        udf5: String
      }
    ]
  },
  OrderStatus: {
    responseCode: Number,
    responseMessage: String,
    requestStatus: {
      uniqueKey: String,
      requestKey: String,
      outputKey: String,
      status: String,
      errorDesc: String,
      errorCode: String
    }
  }
});

const OrderList = mongoose.model("OrderList", orderSchema);

module.exports = { OrderList };
