const customerDataFromApp = {
  "customers": [
    {
      "extCustomerCode": "EXTCUSTCODE",
      "customerName": "VIKRANT SHARMA",
      "isActive": "Yes",
      "customerType": "B2C",
      "address1": "AB-0980 LONG ISLAND",
      "address2": "BLOCK S",
      "address3": "STREET -090",
      "address4": "NEW YORK",
      "phone": "09148998700",
      "altPhone": "088855803",
      "fax": "2-309",
      "email1": "sk14b56@gmail.com",
      "email2": "skbv4in@gmail.com",
      "country": "INDIA",
      "state": "DELHI",
      "city": "NEW DELHI",
      "pinCode": "123300",
      "billAddress1": "DEFENCE STREET VALLEY STREAM",
      "billAddress2": "090-23-A COLONY",
      "billAddress3": "VALLEY ISLE",
      "billAddress4": "NEW YORK",
      "billPhone": "9148225064435",
      "billAltPhone": "0988665693",
      "billFax": "1A-08",
      "billEmail1": "s14sb09@gmail.com",
      "billEmail2": "ssb@e&y.com",
      "billCountry": "INDIA",
      "billState": "DELHI",
      "billCity": "NEW DELHI",
      "billPinCode": "094403",
      "paymentTerms": "7 DAYS",
      "tinNo": "22009933",
      "taxZone": "DELHI",
      "priceZone": "PriceZone One",
      "udf1": "",
      "udf2": "",
      "udf3": "",
      "udf4": "",
      "udf5": "",
      "udf6": "",
      "udf7": "",
      "udf8": "",
      "udf9": "",
      "udf10": "",
      "panNo": "0294828482",
      "gstNo": "3889832",
      "shelflifeonPicking": 1,
      "totalShelfLife": 1,
      "isTaxExempt": "YES",
      "economiczone": "SEZ",
      "creditDays": 5,
      "isTCSApplicable": "YES",
      "tcsPercentage": "0.075",
      "latitude": "54.1123",
      "longitude": "120.2224",
      "geoType": "What3WorDS",
      "geoAddress": "101 add",
      "geoLatitude": "101 latitude",
      "geoLongitude": "101 longitude",
      "addresses": [
        {
          "lineno": "1",
          "address1": "ABC",
          "address2": "XYZ",
          "address3": "PQR",
          "phone": "058484828",
          "altPhone": "028896294",
          "fax": "39492",
          "email1": "abc@gmail.com",
          "email2": "xyz@gmail.com",
          "country": "INDIA",
          "state": "DELHI",
          "city": "NEW DELHI",
          "pinCode": "209723",
          "remarks": "NaN",
          "udf1": "",
          "udf2": "",
          "udf3": "",
          "udf4": "",
          "udf5": "",
          "udf6": "",
          "udf7": "",
          "udf8": "",
          "udf9": "",
          "udf10": "",
          "latitude": "54.1123",
          "longitude": "120.2224"
        }
      ]
    }
  ]
};


// async function getcustomerCode(mobile, otp) {
// }

module.exports = customerDataFromApp;
